### ISSUE TITLE
Support converting touch to keyboard

### ISSUE THREAD

**Issue by btcaboli** [jjackowski/screentouch#9]
I use 'weylus' application to share my desktop operating system in my phone. I tried your application ( for converting touch to mouse ) on my phone and I want to support keyboard beside it. ( I want my phone run a desktop operating system without connecting to any mouse or keyboard only with touch screen )

Hi I am just a newbie in Cpp and I cannot write what I want. I would like to make your application much better.
I want to split the touch screen to 3 areas ( think about a landscape phone that is split to 3 equal areas ) ( 1 row and 3 columns ). The middle one works like a laptop touchpad for mouse.

This is my idea to create a keyboard based on a touch screen.

Other 2 areas are for keyboard each of the 2 areas are split to 6 buttons ( like a grid ( 3 rows * 2 columns ) ) so as we have 2 areas we have 12 buttons. We name each button as its index ( 0-11 ). As keyboards have some 110 buttons and we just have 12 buttons I want to mix 2 sequential press of buttons to produce a key of a keyboard.
* pressing 'btn-0' + 'btn-1' produces pressing key 'a' of the keyboard.

Actually my solution is not perfect but it is better than nothing
As we have websites those running on phone and desktop computers ( it is not impossible to have applications those work for both desktop and mobiles even if one of them have touch screen input and another one have keyboard and mouse ) it might be good to have a same operating system on them with same applications those will give us more opportunities and using their benefits

**Comment by btcaboli** [comment]
Also I recommend to have both support for touching and keyboard and mouse interpretation

I mean like an Android device add a bar in bottom of Linux operating system consist of 4 buttons ( triangle, rectangle, circle + ' a new button to switch to mouse and keyboard interpreting mode ' ) and have a special shortcut in keyboard and mouse interpreting to switch to Android like touch mode

Actually I want to remove laptops style and make a new style for them that is like tablets.
This style is much more portable and comfortable ( no need to open up laptop but just press a turn on button to access the system ) and any one wants a more powerful using can connect mouse and keyboard to his tablet

**Comment by btcaboli** [comment]
Look at the physical keyboards. Each one has its own key map. I mean sometimes some buttons/keys are moved to some where else which make it terrible to interact with different keyboard with different maps but when it is virtual and not physical we can change its map ( like installing a new virtual keyboard in Android ) I mean it is more flexible and we can change keys maps to what we would like

**Comment by jjackowski** [comment]
I'm uncertain this will work well. It is also a major change and growth in scope for the program, so I think it might be better as a new project. Right now, I'm spending my time on work and other projects that have caught my interest, so I'll be passing on this.
